coffee:
  description: Make a coffee
  fields:
    brew_temp:
      required: false
      default: Medium
      selector:
        select:
          options:
            - Low
            - Medium
            - High
    brew_type:
      required: false
      default: Lungo
      selector:
        select:
          options:
            - Ristretto
            - Espresso
            - Lungo
            - Americano
            - label: Hot Water
              value: HOT_WATER
    coffee_ml:
      required: false
      default: 100
      selector:
        number:
          min: 15
          max: 130
          unit_of_measurement: ml
          mode: slider
    water_ml:
      required: false
      default: 100
      selector:
        number:
          min: 25
          max: 300
          unit_of_measurement: ml
          mode: slider
caps:
  description: Manage caps counter
  fields:
    caps:
      required: true
      default: 100
      selector:
        number:
          min: 1
          max: 1000
          step: 1
          mode: box
